spring:
    datasource:
        url: jdbc:mysql://localhost:3306/myjob?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
        username: user
        password: success
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database: mysql
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
            "[format_sql]": true
            "[use_sql_comments]": true
            "[enable_lazy_load_no_trans]": true
            "[default_batch_fetch_size]": 100
logging.level:
    root: info
    "[org.hibernate.SQL]": debug
